---
# tasks file for users
- name: Create users, shell, home directories
  users: 
    name: "{{ username }}"
    uid: "{{ uid | default(omit, True) }}"
    password: "{{ password }}"
    shell: "{{ shell if shell is defined else default_shell }}"
    createhome: yes
