---

# WEB
- hosts: servers
  become: true
  roles:
    - web
# DIRECTORIES
- hosts: servers
  become: true
  roles:
    - directories 
# USERS
- hosts: servers
  become: True
  roles:
    - users
    