---

- hosts: servers
  become: true

  tasks:
    - name: "install apache, HAProxy, Prometheus"
      apt:
        name: ['apache2', 'haproxy', 'prometheus']
        state: present
        update_cache: yes
    - name: Create directories
      file:
        path: /etc/ansible/tmp/pauline
        state: directory